//! Dashboard AI summary (AI.md sections 5-10): a periodic, event-driven, debounced summary of
//! recent alert activity for the dashboard — never generated by a page load, only by this
//! background job (AI.md section 6 calls that a hard requirement). The job wakes on a fixed
//! interval, which doubles as the debounce window (section 8): a burst of alerts inside one tick
//! still produces at most one AI call, on the following tick, never one per alert. It checks
//! whether the alert stream has moved past the state the last stored summary was generated from
//! and, only if it has and the feature is switched on, generates one new summary and stores it.
//! `web_ai.rs`'s summary endpoint only ever reads what is stored here — it never calls a provider
//! itself.

use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;

use anyhow::Result;
use serde::{Deserialize, Serialize};

use crate::store::{EventQuery, SettingsStore, Store};

pub const KEY: &str = "ai_summary";

/// How often the background job checks whether the summary is stale, and so also the
/// debounce/aggregation window AI.md section 8 asks for (it suggests 5-15 minutes).
const CHECK_INTERVAL_SECS: u64 = 600;
/// The summary describes roughly this much recent history, not the full alert table.
const WINDOW_HOURS: i64 = 24;
/// How many of the highest-scored alerts in the window are named individually in the prompt
/// (each needs its own asset lookup); the rest are represented only by their severity counts.
const MAX_HIGHLIGHTS: usize = 8;
/// How many of the most recent alerts are pulled from the store to look for those highlights in.
/// Generous enough to almost always cover a 24h window without scanning the whole alert history.
const CONTEXT_SCAN_LIMIT: usize = 300;

#[derive(Clone, Debug, Default, Serialize, Deserialize, PartialEq)]
pub struct SummaryRecord {
    pub text: String,
    pub generated_at: i64,
    /// The id of the most recent alert this summary was generated from (see `current_version`).
    /// A record that has never been generated has this at 0 and an empty `text`.
    pub source_state_version: i64,
}

pub fn load(store: &dyn SettingsStore) -> Result<SummaryRecord> {
    let raw = store.get_setting(KEY)?;
    Ok(raw.as_deref().and_then(|b| serde_json::from_slice(b).ok()).unwrap_or_default())
}

fn save(store: &dyn SettingsStore, r: &SummaryRecord, now: i64) -> Result<()> {
    store.set_setting(KEY, &serde_json::to_vec(r)?, now)
}

/// Writes a `SummaryRecord` directly, for `web::mod`'s own HTTP test of the read-only endpoint —
/// that test needs a stored summary without running the real background job or a live provider.
#[cfg(test)]
pub fn test_save(store: &dyn SettingsStore, text: &str, generated_at: i64, source_state_version: i64) {
    save(store, &SummaryRecord { text: text.to_string(), generated_at, source_state_version }, generated_at).unwrap();
}

/// The highest alert id that exists: DENIS's own already-scored alert stream is the "meaningful
/// security state" this feature tracks (AI.md section 7) — raw packets and flows never reach here
/// at all, only what the detection engine already decided was worth an `Event`. Deliberately `id`,
/// not `timestamp`: an agent can report a buffered or backfilled alert whose own timestamp is
/// older than one already stored, so ordering by timestamp could pick a stale id and miss that
/// something new arrived. 0 means no alerts exist yet, so there is nothing to summarize.
pub fn current_version(store: &dyn Store) -> Result<i64> {
    store.latest_alert_id()
}

/// Builds the prompt from the store's own recent alerts: severity counts over `WINDOW_HOURS`, and
/// the `MAX_HIGHLIGHTS` highest-scored ones named individually with their device's label.
fn build_prompt(store: &dyn Store, now: i64) -> Result<String> {
    let recent = store.list_events(&EventQuery { alerts_only: true, limit: CONTEXT_SCAN_LIMIT, ..Default::default() })?;
    let cutoff = now - WINDOW_HOURS * 3600;
    let mut in_window: Vec<_> = recent.into_iter().filter(|e| e.timestamp >= cutoff).collect();
    let mut by_severity: std::collections::BTreeMap<&'static str, i64> = [("high", 0), ("medium", 0), ("low", 0)].into_iter().collect();
    for e in &in_window {
        if let Some(n) = by_severity.get_mut(e.severity.as_str()) {
            *n += 1;
        }
    }
    in_window.sort_by_key(|e| std::cmp::Reverse(e.score));
    let mut highlights = Vec::new();
    for e in in_window.iter().take(MAX_HIGHLIGHTS) {
        let label = store.get_asset(e.asset_id)?.map(|a| a.label()).unwrap_or_else(|| format!("device #{}", e.asset_id));
        let summary = e.raw_details["summary"].as_str().unwrap_or_default().to_string();
        highlights.push(crate::ai::SummaryHighlight { kind: e.kind.clone(), severity: e.severity.clone(), score: e.score, device_label: label, summary });
    }
    let counts: Vec<(&str, i64)> = vec![("high", by_severity["high"]), ("medium", by_severity["medium"]), ("low", by_severity["low"])];
    Ok(crate::ai::dashboard_summary_prompt(WINDOW_HOURS, &counts, &highlights))
}

/// One tick: regenerate the summary if it is stale, the feature is on, and a provider is
/// configured. Returns `Ok(true)` if a new summary was actually generated (for the caller's own
/// logging), `Ok(false)` if there was nothing to do. Never called from a request handler — only
/// from `run` below.
fn tick(store: &dyn Store, generating: &AtomicBool) -> Result<bool> {
    let cfg = crate::ai::load(store)?;
    if !cfg.enabled || !cfg.features.dashboard_summary {
        return Ok(false);
    }
    let Some(key) = cfg.key_for(&cfg.default_provider) else { return Ok(false) };
    let _ = key; // presence check only; `ai::summarize` reads the key itself
    let version = current_version(store)?;
    if version == 0 {
        return Ok(false);
    }
    let record = load(store)?;
    if record.source_state_version == version {
        return Ok(false);
    }
    let now = crate::model::now_ts();
    generating.store(true, Ordering::SeqCst);
    let result = (|| -> Result<()> {
        let prompt = build_prompt(store, now)?;
        let (text, tokens) = crate::ai::summarize(&cfg, &cfg.default_provider, &prompt)?;
        save(store, &SummaryRecord { text, generated_at: now, source_state_version: version }, now)?;
        // Best-effort, same tolerance as web_ai's own record_usage: this background job already
        // succeeded at generating the summary, a usage-record failure must not undo that.
        if let Err(e) = crate::ai_usage::record(store, now, tokens) {
            tracing::error!("AI usage record failed: {e:#}");
        }
        Ok(())
    })();
    generating.store(false, Ordering::SeqCst);
    result.map(|()| true)
}

pub async fn run(store: Arc<dyn Store>, generating: Arc<AtomicBool>) {
    let mut tick_timer = tokio::time::interval(std::time::Duration::from_secs(CHECK_INTERVAL_SECS));
    loop {
        tick_timer.tick().await;
        let s = store.clone();
        let g = generating.clone();
        let result = tokio::task::spawn_blocking(move || tick(&*s, &g)).await;
        match result {
            Ok(Ok(true)) => tracing::info!("dashboard AI summary regenerated"),
            Ok(Ok(false)) => {}
            Ok(Err(e)) => tracing::warn!("dashboard AI summary generation failed, will retry at the next check: {e:#}"),
            Err(e) => tracing::warn!("dashboard AI summary generation failed, will retry at the next check: {e}"),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{now_ts, Asset, Event, Mac};
    use crate::store::sqlite::SqliteStore;
    use crate::store::{AssetStore, EventStore};

    fn mem() -> SqliteStore {
        SqliteStore::open_in_memory().unwrap()
    }

    #[test]
    fn version_is_zero_with_no_alerts_and_follows_the_newest_one() {
        let s = mem();
        assert_eq!(current_version(&s).unwrap(), 0);
        let mut a = Asset::new(Mac([0x3c, 0x22, 0xfb, 1, 2, 3]), 100);
        s.save_asset(&mut a).unwrap();
        let mut e = Event { id: 0, agent_id: None, asset_id: a.id, kind: "new_port".into(), timestamp: 100, severity: "medium".into(), score: 50, acked: false, raw_details: serde_json::json!({"summary": "x"}) };
        s.insert_event(&mut e).unwrap();
        assert_eq!(current_version(&s).unwrap(), e.id);
    }

    #[test]
    fn a_tick_with_ai_off_or_unconfigured_does_nothing_and_never_touches_the_record() {
        let s = mem();
        let g = AtomicBool::new(false);
        // no alerts, no config at all
        assert!(!tick(&s, &g).unwrap());
        assert_eq!(load(&s).unwrap(), SummaryRecord::default());

        let mut a = Asset::new(Mac([0x3c, 0x22, 0xfb, 1, 2, 3]), 100);
        s.save_asset(&mut a).unwrap();
        let mut e = Event { id: 0, agent_id: None, asset_id: a.id, kind: "new_port".into(), timestamp: now_ts(), severity: "medium".into(), score: 50, acked: false, raw_details: serde_json::json!({"summary": "x"}) };
        s.insert_event(&mut e).unwrap();
        // AI globally off (default): a real alert exists, but still nothing happens
        assert!(!tick(&s, &g).unwrap());
        assert_eq!(load(&s).unwrap(), SummaryRecord::default());

        // on, feature on, but no provider key: still nothing (no network egress attempted)
        let mut cfg = crate::ai::AiConfig { enabled: true, ..Default::default() };
        cfg.features.dashboard_summary = true;
        crate::ai::save(&s, &cfg, now_ts()).unwrap();
        assert!(!tick(&s, &g).unwrap());
    }

    #[test]
    fn a_stored_summary_stays_stale_until_the_version_it_was_generated_from_matches() {
        let s = mem();
        let mut a = Asset::new(Mac([0x3c, 0x22, 0xfb, 1, 2, 3]), 100);
        s.save_asset(&mut a).unwrap();
        let mut e = Event { id: 0, agent_id: None, asset_id: a.id, kind: "new_port".into(), timestamp: now_ts(), severity: "medium".into(), score: 50, acked: false, raw_details: serde_json::json!({"summary": "x"}) };
        s.insert_event(&mut e).unwrap();
        let v = current_version(&s).unwrap();
        save(&s, &SummaryRecord { text: "stale text".into(), generated_at: 1, source_state_version: v - 1 }, 1).unwrap();
        let r = load(&s).unwrap();
        assert_ne!(r.source_state_version, v, "still considered stale against the real current version");
        assert_eq!(r.text, "stale text", "the last valid summary is still what a reader gets - never blanked out just because it's stale");
    }

    #[test]
    fn the_prompt_only_looks_inside_the_window_and_only_names_the_highest_scored_alerts() {
        let s = mem();
        let mut a = Asset::new(Mac([0x3c, 0x22, 0xfb, 1, 2, 3]), 100);
        s.save_asset(&mut a).unwrap();
        let now = now_ts();
        let mut old = Event { id: 0, agent_id: None, asset_id: a.id, kind: "new_port".into(), timestamp: now - WINDOW_HOURS * 3600 - 10, severity: "high".into(), score: 90, acked: false, raw_details: serde_json::json!({"summary": "too old to count"}) };
        s.insert_event(&mut old).unwrap();
        let mut recent = Event { id: 0, agent_id: None, asset_id: a.id, kind: "new_destination".into(), timestamp: now - 60, severity: "medium".into(), score: 55, acked: false, raw_details: serde_json::json!({"summary": "recent enough"}) };
        s.insert_event(&mut recent).unwrap();
        let p = build_prompt(&s, now).unwrap();
        assert!(p.contains("recent enough"), "{p}");
        assert!(!p.contains("too old to count"), "{p}");
        assert!(p.contains("1 medium"), "{p}");
    }
}
